<link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
 <link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">
 
theme: jekyll-theme-minimal
title: Nicole Westgard's homepage
description: Feel free to bookmark this to keep an eye on my project updates
